; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
lib_deps =
    https://github.com/Sensirion/arduino-i2c-scd30.git
    https://github.com/ArtronShop/ArtronShop_SHT3x.git
    claws/BH1750@^1.3.0
    tzapu/WiFiManager@^2.0.17
    knolleary/PubSubClient@^2.8
    ricmoo/QRCode
    bblanchon/ArduinoJson@^7.2.1
    https://github.com/Bodmer/TFT_eSPI.git
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git

extra_scripts = post:rename_firmware.py
build_flags =
    -DUSER_SETUP_LOADED
    -DST7789_DRIVER
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_RGB_ORDER=TFT_BGR
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=-1
    -DTFT_BL=21
    -DTFT_BACKLIGHT_ON=1
    -DTFT_INVERSION_OFF
    -DLOAD_GLCD
    -DLOAD_FONT2
    -DLOAD_FONT4
    -DLOAD_FONT6
    -DLOAD_FONT7
    -DLOAD_FONT8
    -DLOAD_GFXFF
    -DSMOOTH_FONT
    -DSPI_FREQUENCY=55000000
    -DSPI_READ_FREQUENCY=5000000
    -DSPI_TOUCH_FREQUENCY=2500000


    