; Tool test: nạp vào 1 ESP32 bất kỳ để verify ESP-NOW từ board cảm biến
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
